-- GoreeCloud Drive foundation schema.
-- IDs are generated by the application or identity boundary; this migration does
-- not require a PostgreSQL UUID extension.

BEGIN;

CREATE TABLE accounts (
    id uuid PRIMARY KEY,
    identity_subject text NOT NULL UNIQUE,
    display_name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    disabled_at timestamptz
);

CREATE TABLE spaces (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    kind text NOT NULL CHECK (kind IN ('personal', 'shared', 'private')),
    owner_account_id uuid REFERENCES accounts(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CHECK ((kind = 'personal' AND owner_account_id IS NOT NULL) OR kind <> 'personal')
);

CREATE TABLE space_memberships (
    space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('owner', 'manager', 'editor', 'contributor', 'commenter', 'viewer', 'drop_only')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (space_id, account_id)
);

CREATE TABLE nodes (
    id uuid PRIMARY KEY,
    space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    parent_id uuid REFERENCES nodes(id) ON DELETE RESTRICT,
    kind text NOT NULL CHECK (kind IN ('file', 'folder')),
    name text NOT NULL CHECK (length(name) BETWEEN 1 AND 255),
    created_by uuid NOT NULL REFERENCES accounts(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    modified_at timestamptz NOT NULL DEFAULT now(),
    trashed_at timestamptz,
    UNIQUE (space_id, parent_id, name)
);

CREATE INDEX nodes_space_parent_idx ON nodes (space_id, parent_id);
CREATE INDEX nodes_space_trashed_idx ON nodes (space_id, trashed_at);

CREATE TABLE file_versions (
    id uuid PRIMARY KEY,
    node_id uuid NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    version_number bigint NOT NULL CHECK (version_number > 0),
    object_key text NOT NULL UNIQUE,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    sha256 char(64) NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    media_type text,
    created_by uuid NOT NULL REFERENCES accounts(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (node_id, version_number)
);

CREATE TABLE shares (
    id uuid PRIMARY KEY,
    node_id uuid REFERENCES nodes(id) ON DELETE CASCADE,
    space_id uuid REFERENCES spaces(id) ON DELETE CASCADE,
    created_by uuid NOT NULL REFERENCES accounts(id),
    access_role text NOT NULL CHECK (access_role IN ('editor', 'contributor', 'commenter', 'viewer', 'drop_only')),
    token_hash text UNIQUE,
    expires_at timestamptz,
    revoked_at timestamptz,
    max_uses bigint CHECK (max_uses IS NULL OR max_uses > 0),
    use_count bigint NOT NULL DEFAULT 0 CHECK (use_count >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((node_id IS NOT NULL) <> (space_id IS NOT NULL))
);

CREATE TABLE share_recipients (
    share_id uuid NOT NULL REFERENCES shares(id) ON DELETE CASCADE,
    account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    PRIMARY KEY (share_id, account_id)
);

CREATE TABLE upload_sessions (
    id uuid PRIMARY KEY,
    space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    parent_node_id uuid REFERENCES nodes(id) ON DELETE RESTRICT,
    account_id uuid NOT NULL REFERENCES accounts(id),
    target_name text NOT NULL CHECK (length(target_name) BETWEEN 1 AND 255),
    expected_size_bytes bigint CHECK (expected_size_bytes IS NULL OR expected_size_bytes >= 0),
    received_size_bytes bigint NOT NULL DEFAULT 0 CHECK (received_size_bytes >= 0),
    staging_key text NOT NULL UNIQUE,
    state text NOT NULL CHECK (state IN ('open', 'finalizing', 'complete', 'aborted', 'expired')),
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX upload_sessions_account_state_idx ON upload_sessions (account_id, state);

CREATE TABLE favorites (
    account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    node_id uuid NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (account_id, node_id)
);

CREATE TABLE activity_events (
    id uuid PRIMARY KEY,
    space_id uuid REFERENCES spaces(id) ON DELETE CASCADE,
    actor_account_id uuid REFERENCES accounts(id),
    event_type text NOT NULL,
    target_node_id uuid REFERENCES nodes(id) ON DELETE SET NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX activity_events_space_time_idx ON activity_events (space_id, occurred_at DESC);

CREATE TABLE quotas (
    space_id uuid PRIMARY KEY REFERENCES spaces(id) ON DELETE CASCADE,
    limit_bytes bigint CHECK (limit_bytes IS NULL OR limit_bytes >= 0),
    used_bytes bigint NOT NULL DEFAULT 0 CHECK (used_bytes >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sync_bindings (
    id uuid PRIMARY KEY,
    account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    client_id text NOT NULL,
    mode text NOT NULL CHECK (mode IN ('mirror', 'selective', 'on_demand')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (account_id, client_id, space_id)
);

COMMIT;
